### ISSUE TITLE
CRICKIT Hat for Raspberry Pi does not report SeeSaw temperature

### ISSUE THREAD

**Issue by EAGrahamJr** [adafruit/Adafruit_CircuitPython_seesaw#114]
Version 1.11.7

Invoking the `get_temp()` function on the SeeSaw from the 'Hat always returns **FF FF FF FF** from the `TEMP` register from `STATUS_BASE`. Git blame indicates this was added at the same time as the _moisture_ sensor so perhaps this requires an external connection not available on this board?

**Comment by caternuson** [comment]
Related:
https://forums.adafruit.com/viewtopic.php?t=211227

**Comment by EAGrahamJr** [comment]
Resolved in forum (not supported in this configuration).

Thanks!!!!!
