### ISSUE TITLE
adafruit_seesaw.neopixel.Neopixel should probably be "NeoPixel"

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_seesaw#13]
The NeoPixel class in neopixel.py is spelled "Neopixel" instead of "NeoPixel". Probably should fix this early for consistency. We'll have to update some examples.

@ladyada ok by you? I could make it backward compatible by renaming the class and then doing
```
Neopixel = NeoPixel
```
at the end of the file. But that will be a workaround for forever.

**Comment by ladyada** [comment]
yep!

**Comment by dhalbert** [comment]
Fixed by #14.
