### ISSUE TITLE
Add CircuitPython HW API compatible classes

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_seesaw#2]
SeeSaw functionality should be expose by objects that mimic the native HW API. For example, digital pin reading and writing should match [DigitalInOut](https://circuitpython.readthedocs.io/en/2.x/shared-bindings/digitalio/DigitalInOut.html).

This should include:

- [DigitalInOut](https://circuitpython.readthedocs.io/en/2.x/shared-bindings/digitalio/DigitalInOut.html)
- [PWMOut](https://circuitpython.readthedocs.io/en/2.x/shared-bindings/pulseio/PWMOut.html)
- [AnalogIn](https://circuitpython.readthedocs.io/en/2.x/shared-bindings/analogio/AnalogIn.html)
- [NeoPixel](https://circuitpython.readthedocs.io/projects/neopixel/en/latest/api.html)
- [nvm](https://circuitpython.readthedocs.io/en/2.x/shared-bindings/nvm/ByteArray.html)

**Comment by ladyada** [comment]
PWMout channel has been added :)

**Comment by deanm1278** [comment]
DigitalInOut and AnalogIn have been added as well

**Comment by deanm1278** [comment]
NeoPixel has been added as well
