### ISSUE TITLE
Calls to analog_write require a delay

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_seesaw#20]
More info here:
https://forums.adafruit.com/viewtopic.php?f=19&t=144068
I've also recreated the issue.

Multiple calls to`analog_write` generate an IOError. Adding a `time.sleep` between calls fixes it.

**Comment by deanm1278** [comment]
hey this customer is using an old and now unsupported python library. Please have them switch to using this library (they will also need to set up blinka for running circuitpython code on the raspi). I have just fixed this library for raspberry pi trying to analog write too fast, but they still may run in to problems on other actions that the pi does too fast. If they run in to this problem they could maybe try slowing down I2C communication on the pi.
Here is an example of how to write PWMs using this library
```
from board import SCL, SDA
import busio
from adafruit_seesaw.seesaw import Seesaw
from adafruit_seesaw.pwmout import PWMOut

i2c_bus = busio.I2C(SCL, SDA)

ss = Seesaw(i2c_bus)

pwm1 = PWMOut(ss, 5)
pwm2 = PWMOut(ss, 6)

while True:
    pwm1.duty_cycle = 150
    pwm2.duty_cycle = 230
```
