### ISSUE TITLE
New Board causing OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by wallarug** [adafruit/Adafruit_CircuitPython_seesaw#25]
Hi!

I am experiencing issues with setting the pins when using SeeSaw + new board (Robo HAT MM1) and looking for some assistance from someone with a bit of experience.  I already have CircuitPython running on the board and my next mission is to get SeeSaw compatibility.

SeeSaw device is showing up with i2cdetect.

```
pi@lightshowpi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- 41 -- -- -- -- -- -- -- 49 -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

The error stack trace does not make sense to me as there are lots of calls to many different functions.   It would take me a while to run through the full stack trace.

```
>>> from rmasters_robohat import robohat
>>> robohat.servo_1.angle = 0
>>> ss = robohat.seesaw
>>> BUTTON = robohat.SIGNAL2
>>> ss.pin_mode(BUTTON, ss.INPUT_PULLUP)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_seesaw/seesaw.py", line 177, in pin_mode
    self.pin_mode_bulk_b(1 << (pin - 32), mode)
  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_seesaw/seesaw.py", line 281, in pin_mode_bulk_b
    self.write(_GPIO_BASE, _GPIO_DIRCLR_BULK, cmd)
  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_seesaw/seesaw.py", line 404, in write
    i2c.write(full_buffer)
  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_bus_device/i2c_device.py", line 115, in write
    self.i2c.writeto(self.device_address, buf, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/busio.py", line 65, in writeto
    return self._i2c.writeto(address, buffer, stop=stop)
  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 38, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_PureIO/smbus.py", line 244, in write_bytes
    self._device.write(buf)
OSError: [Errno 5] Input/output error
```

Please point me in the right direction to see if this can be solved.  Most of the software is based on pre-existing Adafruit Libraries and customised for this board (Robo HAT MM1).

You can find the relevant SeeSaw files here:
[rmasters_robohat.py](https://github.com/robotics-masters/mm1-hat-seesaw/blob/master/circuitpython/Adafruit_CircuitPython_RoboHat/rmasters_robohat.py)
[robohat.py](https://github.com/robotics-masters/mm1-hat-seesaw/blob/master/circuitpython/Adafruit_CircuitPython_seesaw/robohat.py)
[board_config.h](https://github.com/robotics-masters/mm1-hat-seesaw/blob/master/firmware/mm1_hat/board_config.h)

Issue on Repo:  https://github.com/robotics-masters/mm1-hat-seesaw/issues/6

SeeSaw is such a cool little library to use!

**Comment by ladyada** [comment]
thanks - that can happen if you send it a bad command, that doesnt match what seesaw is expecting for its pin setups. the CRICKIT hat uses seesaw so you can look at how that is configured, then attach a debugger or turn on debug ouput to the seesaw chip and see what data its getting or expecting. since this doesn't seem to be a bug in our library, this issue will be closed.
