### ISSUE TITLE
How to use on raspberry

### ISSUE THREAD

**Issue by Phill93** [adafruit/Adafruit_CircuitPython_seesaw#27]
How do I use this library on a raspberry?

**Comment by ladyada** [comment]
@kattni we need to update the guide
@Phill93 you can follow https://learn.adafruit.com/circuitpython-on-raspberrypi-linux and the pip install this library

**Comment by kattni** [comment]
@Phill93 The guide has been updated to reflect using the current library, including a code example. Please visit the guide for more information. https://learn.adafruit.com/adafruit-seesaw-atsamd09-breakout/raspberry-pi-wiring-test
