### ISSUE TITLE
seesaw uart messing with rpi serial0 uart.

### ISSUE THREAD

**Issue by jgoergen** [adafruit/Adafruit_CircuitPython_seesaw#54]
I'm trying to read a sensor over standard 'minicom' serial0 UART on the Raspberry Pi, but the data only comes in when I hold down the reset button on the Crickit. If I plug a USB cable into the seesaw USB port and 'Putty into' the serial adapter, then connect to the Rasbperry Pi serial0 UART with screen, I can type data back and forth. So I know the Seesaw is, by default, connected directly to the Raspberry Pi UART pins. 

Is there some way to disable this without physically cutting the lines on the Crickit board?
Thank you!

**Comment by ladyada** [comment]
duplicate
