### ISSUE TITLE
Product ID 4991 (I2C rotary encoder)

### ISSUE THREAD

**Issue by panellaj** [adafruit/Adafruit_CircuitPython_seesaw#67]
When turning the encoder clockwise, the number is increasing with a negative number.  This is assuming the start position is 0.

https://forums.adafruit.com/viewtopic.php?f=19&t=179100#p872488

**Comment by ladyada** [comment]
'fixed' in https://github.com/adafruit/Adafruit_CircuitPython_seesaw/pull/75
