### ISSUE TITLE
Object instantiation causes a reset

### ISSUE THREAD

**Issue by pshanesmith** [adafruit/Adafruit_CircuitPython_seesaw#79]
Having a reset on the board when you create an instance of the Seesaw object limits a lot of applications of the device.  The libraries for other breakouts don't do this.  Most assume the current state persists unless you power off or reset.

Having the option to not reset would be beneficial.

In my example, I have separate scripts that are called by a master program.  In the case, I trigger a PWM signal on one pin.  Calling another script that reads the ADC on another pin resets the PWM signal.

**Comment by tannewt** [comment]
Drivers should reset the peripheral to ensure the script runs the same each time. Leaving previous state can cause the script to change behavior without it being obvious why.

Why do you need to share state across scripts? A plugin system could achieve similar flexibility without restarting everything.

I agree though that there should be an option to turn off the reset. Perhaps a `reset` keyword arg that defaults to True would be sufficient. I think this will be more common as folks do deep sleeps where the scripts restart after wake up.

**Comment by pshanesmith** [comment]
Thanks for the response.  Many of the breakouts offered by Adafruit do not reset the device.

In my case, I was attempting to run small scripts in response to sensor input.  This is part of an an application developed by someone else that polls using input modules and responds using output modules.  There's no option to retain objects between polling and output cycles.

**Comment by tekktrik** [comment]
I think this was fixed by the linked commit above.  Is that correct, @ladyada?

**Comment by ladyada** [comment]
yep!
