### ISSUE TITLE
two encoders at once?

### ISSUE THREAD

**Issue by troylball** [adafruit/Adafruit_CircuitPython_seesaw#93]

**Comment by ladyada** [comment]
@jedgarpark or @kattni may already have an example they can add

**Comment by jedgarpark** [comment]
I built a version of this in Arduino, but I can work on a CircuitPython example.

**Comment by troylball** [comment]
So what are my next steps?  Search their git hub repositories and reach out to them directly?  Can I / should I refer to this email and say that Adafruit suggests I reach out?




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jedgarpark** [comment]
@troylball I'll try to put together an example later today.

**Comment by troylball** [comment]
Thanks John, that would be appreciated,  it does not need to bee too intrecit.  My end goal is to use these with a TEA 5767 FM chip to convert an old radio.  One button volume one button frequency.  I am guessing I could run two programs at the same time but thought it would nice to see it all together.

I see your other e-mail came in thanks for that


Thanks,

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jedgarpark** [comment]
@troylball here's an example of two encoders https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/main/Seesaw_QT_Rotary_Encoder_Multiples/code.py

**Comment by ladyada** [comment]
@jedgarpark  this should go into this library as an example, @kattni can help if needed

**Comment by jedgarpark** [comment]
it is now in the library examples
