### ISSUE TITLE
No I2C device found at address: 0x36 that is suggested in the code

### ISSUE THREAD

**Issue by Absol3000** [adafruit/Adafruit_CircuitPython_seesaw#99]
I installed the seesaw library to my itsybitsy. I tried the 7x version and the version for older systems but the dress of the I2C device is not found in both files. I dont know how to fix this problem so i hope someone can help. I wanted to view the mpy file to find it but those files are already encoded so i cannot access them. If somebody knows a solution then that would be great!

![image](https://user-images.githubusercontent.com/99337517/167104763-e63213e8-767b-44f8-8d94-5d935d1eeadc.png)
![image](https://user-images.githubusercontent.com/99337517/167104675-bae7bc53-12d0-42a1-8935-f04095818cfa.png)
![setup](https://user-images.githubusercontent.com/99337517/167104993-f5435beb-e346-44da-a44a-c0f5bdc360b0.jpeg)

**Comment by caternuson** [comment]
That does not look like an Adafruit Soil Sensor:
https://www.adafruit.com/product/4026
which is what the seesaw library is expecting.

Please contact the manufacturer of the soil sensor.
